"""create wishlist items table

Revision ID: 6ffc25efce3e
Revises: 6b7c8d9e0f12
Create Date: 2026-06-10 10:59:07.283622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '6ffc25efce3e'
down_revision: Union[str, Sequence[str], None] = '6b7c8d9e0f12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wishlist_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'product_id', name='uq_wishlist_user_product')
    )
    op.create_index('ix_wishlist_items_user_id', 'wishlist_items', ['user_id'], unique=False)
    op.drop_constraint(op.f('forum_threads_slug_key'), 'forum_threads', type_='unique')
    op.drop_index(op.f('ix_forum_threads_slug'), table_name='forum_threads')
    op.create_index(op.f('ix_forum_threads_slug'), 'forum_threads', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_forum_threads_slug'), table_name='forum_threads')
    op.create_index(op.f('ix_forum_threads_slug'), 'forum_threads', ['slug'], unique=False)
    op.create_unique_constraint(op.f('forum_threads_slug_key'), 'forum_threads', ['slug'], postgresql_nulls_not_distinct=False)
    op.drop_index('ix_wishlist_items_user_id', table_name='wishlist_items')
    op.drop_table('wishlist_items')
    # ### end Alembic commands ###
