"""add_hitl_and_human_flag

Revision ID: 7513a006343d
Revises: 9ecc120d4979
Create Date: 2026-06-15 23:03:17.377639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7513a006343d'
down_revision: Union[str, Sequence[str], None] = '9ecc120d4979'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first in PostgreSQL
    chat_routing_status_enum = sa.Enum('ai', 'pending_human', 'human', name='chatroutingstatusenum')
    chat_routing_status_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('chat_messages', sa.Column('is_from_human', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('chat_sessions', sa.Column('routing_status', chat_routing_status_enum, server_default='ai', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'routing_status')
    op.drop_column('chat_messages', 'is_from_human')
    op.execute("DROP TYPE chatroutingstatusenum")
    # ### end Alembic commands ###
