"""add sold_count avg_rating review_count to products

Revision ID: 87d3f21ba4b9
Revises: e1f2a3b4c5d6
Create Date: 2026-04-28 23:11:04.747746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87d3f21ba4b9'
down_revision: Union[str, Sequence[str], None] = 'e1f2a3b4c5d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('products', sa.Column('sold_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('products', sa.Column('avg_rating', sa.Numeric(precision=3, scale=2), nullable=True))
    op.add_column('products', sa.Column('review_count', sa.Integer(), server_default='0', nullable=False))

    # Backfill sold_count from paid/completed orders
    op.execute("""
        UPDATE products p
        SET sold_count = COALESCE((
            SELECT SUM(oi.quantity)
            FROM order_items oi
            JOIN orders o ON o.id = oi.order_id
            WHERE oi.product_id = p.id
              AND o.payment_status = 'paid'
        ), 0)
    """)

    # Backfill avg_rating and review_count from reviews
    op.execute("""
        UPDATE products p
        SET avg_rating = sub.avg_r,
            review_count = sub.cnt
        FROM (
            SELECT product_id,
                   ROUND(AVG(rating)::numeric, 2) AS avg_r,
                   COUNT(*) AS cnt
            FROM reviews
            GROUP BY product_id
        ) sub
        WHERE p.id = sub.product_id
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'review_count')
    op.drop_column('products', 'avg_rating')
    op.drop_column('products', 'sold_count')
    # ### end Alembic commands ###
