"""add attr_key attr_value to product_images

Revision ID: d6576314f43b
Revises: 8d7a00ebaf38
Create Date: 2026-04-20 00:40:37.729897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6576314f43b'
down_revision: Union[str, Sequence[str], None] = '8d7a00ebaf38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_images', sa.Column('attr_key', sa.String(), nullable=True))
    op.add_column('product_images', sa.Column('attr_value', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_images', 'attr_value')
    op.drop_column('product_images', 'attr_key')
    # ### end Alembic commands ###
