"""add context summary to chat session

Revision ID: dc9c973577fb
Revises: b71e2d3c4f5a
Create Date: 2026-06-24 14:15:14.416041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'dc9c973577fb'
down_revision: Union[str, Sequence[str], None] = 'b71e2d3c4f5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('context_summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'context_summary')
    # ### end Alembic commands ###
